services:

  db:
    image: mariadb:11.4
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"

  meilisearch:
    image: getmeili/meilisearch:v1.12
    volumes:
      - ./data.ms:/data.ms
    ports:
      - "7700:7700"

  redis:
      image: redis:7.2.4
      ports:
        - "6379:6379"
      environment:
        REDIS_PORT: 6379
        ALLOW_EMPTY_PASSWORD: yes
